name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.1.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.1.4
      with:
        name: programa

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: lucasgomide
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v5.2.0
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: lucasgomide/go_ci:${{ github.ref_name }}
