name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.1.0

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: lucasgomide
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      
